"""empty message

Revision ID: 69a1d1064cc5
Revises: 8103f0fd41f9
Create Date: 2025-01-31 13:43:03.414833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a1d1064cc5'
down_revision: Union[str, None] = '8103f0fd41f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'api_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'api_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
